server:
  context-path: /log
  port: 9002
  #tomcat:
    #uri-encoding: UTF-8
  session:
    timeout: 900

verCode: 1.1.0.1170 
envName: test
#isVerifySign:if check sign
isVerifySign: false
isAuthLogin: true
isSaveLog: true
isProduct: false
isSendMQ: true
logQueueName: logMQ
businessQueueName: businessTestMQ

spring:  
  data:
    mongodb:
      uri: mongodb://192.168.0.123:27017/serverLog
  
  rabbitmq:
    host: 192.168.0.11
    port: 5672
    username: guest
    password: guest 
      

    